name: Render

on:
  push

jobs:
  render:
    name: Render header
    runs-on: ubuntu-latest
    container: nytimes/blender:2.83-cpu-ubuntu18.04
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: blender -b render.blend -P $GITHUB_WORKSPACE/script.py -f 1
      - uses: actions/upload-artifact@v2
        with:
          name: frames
          path: /tmp/*.png

  animate:
    name: Sequence to GIF
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg
    needs: render
    steps:
      - name: Download frames
        uses: actions/download-artifact@v1
        with:
          name: frames
      - name: Convert to GIF
        run: ffmpeg -i frames/%04d.png -r 24 header.gif -y   
      - uses: actions/upload-artifact@v2
        with:
          name: header
          path: header.gif


  commit:
    name: Commit & push header
    runs-on: ubuntu-latest
    needs: animate
    steps:
      - uses: actions/checkout@v2
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: header
      - name: Rename old file
        run: cp header.gif "Header `date`.gif"
      - name: Copy new file
        run: cp header/header.gif header.gif
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Leon Koole's Blender Render
          author_email: leon@koole.io
          message: "Generated new animation"
          add: "*.gif"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}